// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbxOdIJDTkUxoMsDZgv7BTCN-rQxAf1Aw',
    appId: '1:1091889402650:web:bbf4468b5188ec9f4d52a3',
    messagingSenderId: '1091889402650',
    projectId: 'whatsapp-clone-app-fd22b',
    authDomain: 'whatsapp-clone-app-fd22b.firebaseapp.com',
    storageBucket: 'whatsapp-clone-app-fd22b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALNWwzddnC4gqYTeWb20D4T_yhPnqxaAw',
    appId: '1:1091889402650:android:0400072fbccea0884d52a3',
    messagingSenderId: '1091889402650',
    projectId: 'whatsapp-clone-app-fd22b',
    storageBucket: 'whatsapp-clone-app-fd22b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbYFQ2NniSehKPwL0mQo0RfyH6S7VYGrM',
    appId: '1:1091889402650:ios:0eafef75c629b5414d52a3',
    messagingSenderId: '1091889402650',
    projectId: 'whatsapp-clone-app-fd22b',
    storageBucket: 'whatsapp-clone-app-fd22b.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbYFQ2NniSehKPwL0mQo0RfyH6S7VYGrM',
    appId: '1:1091889402650:ios:df43b5b1764bfb4b4d52a3',
    messagingSenderId: '1091889402650',
    projectId: 'whatsapp-clone-app-fd22b',
    storageBucket: 'whatsapp-clone-app-fd22b.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
